
import Header from "@/components/base/Header"
import Menu from "@/components/base/Menu"
import Side from "@/components/base/Side"
import MaxWidthWrapper from "@/components/ui/MaxWidthWrapper"
import '@/styles/globals.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="bg-gradient-to-r from-gray-300 to-slate-500">
        <Header />
        <MaxWidthWrapper className="contactGeneral">
          <div className="grid grid-cols-5 gap-4">
            <div className="col-span-1"> <Menu /></div>
            <div className="col-span-3">{children}</div>
            <div className="col-span-1"> <Side src1={"/BuguTas.png"} src2={"/BUGU.png"} /></div>
          </div>
        </MaxWidthWrapper>
      </body>

    </html>
  )
}
